FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
COPY app.py app.py
COPY test_app.py test_app.py
COPY .env .env

RUN pip install -r requirements.txt

CMD ["python", "-m", "unittest", "test_app.py"]
